import Head from 'next/head'

import EventsCalendar from '@/components/calendar/EventsCalendar'

const Events = () => {
  return (
    <>
      <Head>
        <title>Bumblebee Playspace | Calendar</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main>
        <section className="mx-auto my-16 flex min-h-screen max-w-7xl flex-col items-center px-8">
          <h1 className="mb-8 text-5xl font-bold md:text-7xl">Calendar</h1>
          <div className="mb-16 w-full">
            <EventsCalendar />
          </div>
        </section>
      </main>
    </>
  )
}

export default Events
