import Head from 'next/head'

import CollageHero from '@/components/heroes/Collage'
import PricingHero from '@/components/heroes/Pricing'
import LocationHero from '@/components/heroes/Location'
import PartyHero from '@/components/heroes/Parties'

const Home = () => {
  return (
    <>
      <Head>
        <title>Bumblebee Playspace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CollageHero />
        <PartyHero />
        <PricingHero />
        <LocationHero />
      </main>
    </>
  )
}

export default Home
