import Head from 'next/head'
import PartyInfoHero from '@/components/heroes/PartyInfo'
import PartyIntroHero from '@/components/heroes/PartyIntro'

const Parties = () => {
  return (
    <>
      <Head>
        <title>Bumblebee Playspace | Parties</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="min-h-screen bg-amber-100 lg:snap-y">
        <PartyIntroHero />
        <PartyInfoHero />
      </main>
    </>
  )
}

export default Parties
