import Head from 'next/head'

import AboutHero from '@/components/heroes/About'
import FeaturesHero from '@/components/heroes/Features'
import OpenPlayHero from '@/components/heroes/OpenPlay'
import GalleryHero from '@/components/heroes/Gallery'
import MembershipHero from '@/components/heroes/Memberships'
//import RoomsHero from '../components/heroes/rooms/RoomsHero'

const Visit = () => {
  return (
    <>
      <Head>
        <title>Bumblebee Playspace | Play</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AboutHero />
        <FeaturesHero />
        <GalleryHero />
        <OpenPlayHero />
        <MembershipHero />
        {/* <RoomsHero /> */}
      </main>
    </>
  )
}

export default Visit
